### ISSUE TITLE
Review terminology for consistency

### ISSUE THREAD

**Issue by tracymiranda** [sigstore/architecture-docs#4]
Do you mean "identity of the signer" instead of "identity of the client"? 'client' has been consistently used to refer to the signing/verification tool

_Originally posted by @chinenyeokafor in https://github.com/sigstore/architecture-docs/pull/3#discussion_r1690390953_

**Comment by haydentherapper** [comment]
Answered in the PR.

**Comment by tracymiranda** [comment]
Thanks. Fixed in PR.
